In [260]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [261]:
import io
%cd "C:\Users\v-rakul\Desktop"

C:\Users\v-rakul\Desktop


In [262]:
train=pd.read_csv(r"C:\Users\v-rakul\Desktop\train_v9rqX0R.csv")

In [263]:
train.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [264]:
test=pd.read_csv(r"C:\Users\v-rakul\Desktop\test_AbJTz2l.csv")

In [265]:
train['Item_Fat_Content']=train['Item_Fat_Content'].replace({'low fat':'Low Fat'})

In [266]:
test['Item_Fat_Content']=test['Item_Fat_Content'].replace({'low fat':'Low Fat'})

In [267]:
train['Item_Fat_Content']=train['Item_Fat_Content'].replace({'LF':'Low Fat'})

In [268]:
test['Item_Fat_Content']=test['Item_Fat_Content'].replace({'LF':'Low Fat'})

In [269]:
train['Item_Fat_Content']=train['Item_Fat_Content'].replace({'reg':'Regular'})

In [270]:
test['Item_Fat_Content']=test['Item_Fat_Content'].replace({'reg':'Regular'})

In [271]:
train['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [272]:
test['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [273]:
train["OutletAge"]=2021-train["Outlet_Establishment_Year"]

In [274]:
test["OutletAge"]=2021-test["Outlet_Establishment_Year"]

In [275]:
combineddf=[train,test]

In [276]:
for data in combineddf:
    data['Item_Weight'].fillna(data['Item_Weight'].mean(),inplace = True)
    data['Outlet_Size'].fillna('Medium',inplace = True)

In [277]:
col = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

In [278]:
train_datar = pd.get_dummies(train, columns = col, drop_first = True)
test_datar = pd.get_dummies(test, columns = col,drop_first = True)

In [279]:
feat_cols = ['Item_Weight', 'Item_Visibility', 'Item_MRP','OutletAge' ,
       'Item_Fat_Content_Regular', 'Item_Type_Breads', 'Item_Type_Breakfast',
       'Item_Type_Canned', 'Item_Type_Dairy', 'Item_Type_Frozen Foods',
       'Item_Type_Fruits and Vegetables', 'Item_Type_Hard Drinks',
       'Item_Type_Health and Hygiene', 'Item_Type_Household', 'Item_Type_Meat',
       'Item_Type_Others', 'Item_Type_Seafood', 'Item_Type_Snack Foods',
       'Item_Type_Soft Drinks', 'Item_Type_Starchy Foods',
       'Outlet_Size_Medium', 'Outlet_Size_Small',
       'Outlet_Location_Type_Tier 2', 'Outlet_Location_Type_Tier 3',
       'Outlet_Type_Supermarket Type1', 'Outlet_Type_Supermarket Type2',
       'Outlet_Type_Supermarket Type3']

In [280]:
train_datar.head()

Item_Identifier  Item_Weight  Item_Visibility  Item_MRP Outlet_Identifier  \
0           FDA15         9.30         0.016047  249.8092            OUT049   
1           DRC01         5.92         0.019278   48.2692            OUT018   
2           FDN15        17.50         0.016760  141.6180            OUT049   
3           FDX07        19.20         0.000000  182.0950            OUT010   
4           NCD19         8.93         0.000000   53.8614            OUT013   

   Outlet_Establishment_Year  Item_Outlet_Sales  OutletAge  \
0                       1999          3735.1380         22   
1                       2009           443.4228         12   
2                       1999          2097.2700         22   
3                       1998           732.3800         23   
4                       1987           994.7052         34   

   Item_Fat_Content_Regular  Item_Type_Breads  ...  Item_Type_Snack Foods  \
0                         0                 0  ...                      0   
1                         1                 0  ...                      0   
2                         0                 0  ...                      0   
3                         1                 0  ...                      0   
4                         0                 0  ...                      0   

   Item_Type_Soft Drinks  Item_Type_Starchy Foods  Outlet_Size_Medium  \
0                      0                        0                   1   
1                      1                        0                   1   
2                      0                        0                   1   
3                      0                        0                   1   
4                      0                        0                   0   

   Outlet_Size_Small  Outlet_Location_Type_Tier 2  \
0                  0                            0   
1                  0                            0   
2                  0                            0   
3                  0                            0   
4                  0                            0   

   Outlet_Location_Type_Tier 3  Outlet_Type_Supermarket Type1  \
0                            0                              1   
1                            1                              0   
2                            0                              1   
3                            1                              0   
4                            1                              1   

   Outlet_Type_Supermarket Type2  Outlet_Type_Supermarket Type3  
0                              0                              0  
1                              1                              0  
2                              0                              0  
3                              0                              0  
4                              0                              0  

[5 rows x 31 columns]

In [281]:
test.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
OutletAge                    0
dtype: int64

In [282]:
train.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
OutletAge                    0
dtype: int64

In [283]:
x = train_datar[feat_cols]
y = train_datar['Item_Outlet_Sales']

In [284]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 0)

In [285]:
y.head()

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

##### MLR

In [286]:
from sklearn.linear_model import LinearRegression

In [287]:
mlr_model=LinearRegression()

In [288]:
mlr_model.fit(x_train,y_train)

LinearRegression()

In [289]:
y_pred=mlr_model.predict(x_test)

In [290]:
y_pred

array([ 2458.96375526,  2537.68459598,  2245.80639585, ...,
        4263.6143873 , -1058.62657846,  5418.56893125])

In [220]:
from sklearn.metrics import mean_squared_error

In [221]:
mse=mean_squared_error(y_test,y_pred)

In [222]:
mse

1281773.980313162

In [223]:
rmse=np.sqrt(mse)

In [224]:
rmse

1132.154574390424

In [57]:
from sklearn.metrics import r2_score

In [58]:
r2_score(y_test,y_pred)

0.562065073173319

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
lr_accuracy = round(mlr_model.score(x_train,y_train) * 100,2)
lr_accuracy

56.35

#### SVM

In [225]:
from sklearn.preprocessing import MinMaxScaler

In [226]:
#Init
sc=MinMaxScaler()

In [227]:
x_train=sc.fit_transform(x_train)

In [228]:
x_train

array([[0.4943522 , 0.02656085, 0.39156208, ..., 0.        , 0.        ,
        1.        ],
       [0.84221494, 0.0445281 , 0.08804134, ..., 1.        , 0.        ,
        0.        ],
       [0.67252158, 0.37038999, 0.1245    , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.53259899, 0.        , 0.19994194, ..., 1.        , 0.        ,
        0.        ],
       [0.84221494, 0.31940718, 0.38250345, ..., 1.        , 0.        ,
        0.        ],
       [0.56236975, 0.12593333, 0.63995935, ..., 1.        , 0.        ,
        0.        ]])

In [229]:
x_test=sc.transform(x_test)

In [230]:
x_test

array([[0.59214052, 0.27394257, 0.54444512, ..., 1.        , 0.        ,
        0.        ],
       [0.4943522 , 0.02903478, 0.14117668, ..., 0.        , 0.        ,
        1.        ],
       [0.41351593, 0.05402713, 0.41754358, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.49091992, 0.21182345, 0.98360261, ..., 1.        , 0.        ,
        0.        ],
       [0.4943522 , 0.49592291, 0.09892088, ..., 0.        , 0.        ,
        0.        ],
       [0.4943522 , 0.06657768, 0.91562252, ..., 0.        , 0.        ,
        1.        ]])

In [231]:
from sklearn.svm import SVR

In [232]:
#kernel=linear for linear svm
svm_model=SVR(C= 1001, kernel= 'poly')

In [233]:
svm_model.fit(x_train,y_train)

SVR(C=1001, kernel='poly')

In [234]:
y_pred=svm_model.predict(x_test)

In [235]:
from sklearn.metrics import mean_squared_error

In [236]:
mse=mean_squared_error(y_test,y_pred)

In [237]:
mse

1196448.0731505

In [238]:
rmse=np.sqrt(mse)

In [239]:
rmse

1093.8226881677394

In [141]:
from sklearn.metrics import r2_score

In [142]:
r2=r2_score(y_test,y_pred)
r2

0.5912177908003151

In [118]:
svr_model1=SVR()

In [119]:
from sklearn.model_selection import GridSearchCV

In [133]:
param_grid={
            'kernel': ['rbf','linear', 'poly', 'sigmoid'],
            'C': [1, 5, 170, 1001]
            
        }

In [134]:
gsv=GridSearchCV(svr_model1,param_grid,scoring='r2',n_jobs=8,verbose=10,cv=5)

In [135]:
gsv.fit(x_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


GridSearchCV(cv=5, estimator=SVR(), n_jobs=8,
             param_grid={'C': [1, 5, 170, 1001],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             scoring='r2', verbose=10)

In [136]:
gsv.best_params_

{'C': 1001, 'kernel': 'poly'}

In [143]:
from sklearn.metrics import accuracy_score

In [145]:
lr_accuracy = round(svm_model.score(x_train,y_train) * 100,2)
lr_accuracy

61.6

##### DT

In [240]:
from sklearn.tree import DecisionTreeRegressor

In [241]:
dt_model=DecisionTreeRegressor(criterion= 'mse',
 max_depth= 6,
 max_leaf_nodes= 100,
 min_samples_leaf= 40,
 min_samples_split= 10)

In [242]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=6, max_leaf_nodes=100, min_samples_leaf=40,
                      min_samples_split=10)

In [243]:
y_pred=dt_model.predict(x_test)

In [244]:
y_pred

array([2673.41988072, 1714.75299403, 2153.76615636, ..., 4496.1474    ,
        164.22213077, 6328.16083056])

In [245]:
from sklearn.metrics import mean_squared_error

In [246]:
mse=mean_squared_error(y_test,y_pred)

In [247]:
mse

1211858.9569370598

In [248]:
rmse=np.sqrt(mse)
rmse

1100.8446561332166

In [169]:
from sklearn.metrics import r2_score

In [170]:
r2=r2_score(y_test,y_pred)
r2

0.585952459808222

In [159]:
from sklearn.model_selection import GridSearchCV

In [160]:
dt_model2=DecisionTreeRegressor()

In [161]:
param_grid = {"criterion": ["mse", "mae"],
              "min_samples_split": [10, 20, 40],
              "max_depth": [2, 6, 8],
              "min_samples_leaf": [20, 40, 100],
              "max_leaf_nodes": [5, 20, 100],
              }

In [162]:
gsv=GridSearchCV(dt_model2,param_grid,scoring='r2',n_jobs=8,verbose=10,cv=5)

In [163]:
gsv.fit(x_train,y_train)

Fitting 5 folds for each of 162 candidates, totalling 810 fits


GridSearchCV(cv=5, estimator=DecisionTreeRegressor(), n_jobs=8,
             param_grid={'criterion': ['mse', 'mae'], 'max_depth': [2, 6, 8],
                         'max_leaf_nodes': [5, 20, 100],
                         'min_samples_leaf': [20, 40, 100],
                         'min_samples_split': [10, 20, 40]},
             scoring='r2', verbose=10)

In [164]:
gsv.best_params_

{'criterion': 'mse',
 'max_depth': 6,
 'max_leaf_nodes': 100,
 'min_samples_leaf': 40,
 'min_samples_split': 10}

#### RandomForest 

In [171]:
from sklearn.ensemble import RandomForestRegressor

In [184]:
rf_model=RandomForestRegressor( criterion= 'mse',
 max_depth= 6,
 max_leaf_nodes= 100,
 min_samples_leaf= 40,
 min_samples_split= 20,random_state=42)

In [185]:
rf_model.fit(x_train,y_train)

RandomForestRegressor(max_depth=6, max_leaf_nodes=100, min_samples_leaf=40,
                      min_samples_split=20, random_state=42)

In [249]:
y_pred=rf_model.predict(x_test)

In [250]:
from sklearn.metrics import mean_squared_error

In [251]:
mse=mean_squared_error(y_test,y_pred)
mse

1190112.6246173887

In [252]:
rmse=np.sqrt(mse)
rmse

1090.9228316509782

In [187]:
from sklearn.metrics import r2_score

In [188]:
r2=r2_score(y_test,y_pred)
r2

0.5933823800589335

In [178]:
from sklearn.model_selection import GridSearchCV

In [179]:
rf_model1=DecisionTreeRegressor()

In [180]:
param_grid = {"criterion": ["mse", "mae"],
              "min_samples_split": [10, 20, 40],
              "max_depth": [2, 6, 8],
              "min_samples_leaf": [20, 40, 100],
              "max_leaf_nodes": [5, 20, 100],
              }

In [181]:
gsv=GridSearchCV(rf_model1,param_grid,scoring='r2',n_jobs=8,verbose=10,cv=5)

In [182]:
gsv.fit(x_train,y_train)

Fitting 5 folds for each of 162 candidates, totalling 810 fits


GridSearchCV(cv=5, estimator=DecisionTreeRegressor(), n_jobs=8,
             param_grid={'criterion': ['mse', 'mae'], 'max_depth': [2, 6, 8],
                         'max_leaf_nodes': [5, 20, 100],
                         'min_samples_leaf': [20, 40, 100],
                         'min_samples_split': [10, 20, 40]},
             scoring='r2', verbose=10)

In [183]:
gsv.best_params_

{'criterion': 'mse',
 'max_depth': 6,
 'max_leaf_nodes': 100,
 'min_samples_leaf': 40,
 'min_samples_split': 20}

#### XGBoost

In [2]:
from xgboost import XGBRegressor

In [3]:
XGB = XGBRegressor(colsample_bytree= 0.7,
 learning_rate= 0.03,
 max_depth= 5,
 min_child_weight= 4,
 n_estimators=500,
 nthread= 4,
 objective= 'reg:linear',
 silent= 1,
 subsample= 0.7)

In [4]:
XGB.fit(x_train, y_train)

NameError: name 'x_train' is not defined

In [256]:
y_pred = XGB.predict(x_test)

In [257]:
from sklearn.metrics import mean_squared_error

In [258]:
mse=mean_squared_error(y_test,y_pred)
mse

1254605.4286318964

In [259]:
rmse=np.sqrt(mse)
rmse

1120.0917054562526

In [203]:
from sklearn.metrics import r2_score

In [204]:
r2=r2_score(y_test,y_pred)
r2

0.5713475659335597

In [195]:
from sklearn.model_selection import GridSearchCV

In [196]:
param_grid = {'nthread':[4], #when use hyperthread, xgboost may become slower
              'objective':['reg:linear'],
              'learning_rate': [.03, 0.05, .07], #so called `eta` value
              'max_depth': [5, 6, 7],
              'min_child_weight': [4],
              'silent': [1],
              'subsample': [0.7],
              'colsample_bytree': [0.7],
              'n_estimators': [500]}

In [197]:
gsv=GridSearchCV(XGB,param_grid,scoring='r2',n_jobs=8,verbose=10,cv=5)

In [198]:
gsv.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[03:37:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
[03:37:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573: 
Parameters: { "silent" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                    colsample_bylevel=1, colsample_bynode=1,
                                    colsample_bytree=1, gamma=0, gpu_id=-1,
                                    importance_type='gain',
                                    interaction_constraints='',
                                    learning_rate=0.300000012, max_delta_step=0,
                                    max_depth=6, min_child_weight=1,
                                    missing=nan, monotone_constraints='()',
                                    n_estimators=100, n_jobs=8,
                                    num_parallel_...
                                    reg_alpha=0, reg_lambda=1,
                                    scale_pos_weight=1, subsample=1,
                                    tree_method='exact', validate_parameters=1,
                                    verbosity=None),
             n_jobs=8,
   

In [199]:
gsv.best_params_

{'colsample_bytree': 0.7,
 'learning_rate': 0.03,
 'max_depth': 5,
 'min_child_weight': 4,
 'n_estimators': 500,
 'nthread': 4,
 'objective': 'reg:linear',
 'silent': 1,
 'subsample': 0.7}